dist : trusty
language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker
# sudo required for docker based testing
sudo: required 

env:
  global:
    - DB_NAME=test_niassa_meta_db
    - DB_USER=postgres
    - DB_PASSWORD=testpassword
    - DB_HOST=127.0.0.1
    - DB_PORT=5433


before_install:
- cp .travis/toolchains.xml ~/.m2
- echo "MAVEN_OPTS='-Xms6144m -Xmx6144m'" > ~/.mavenrc
- mkdir ~/.seqware
- cp .travis/settings ~/.seqware/settings

install:
- travis_wait mvn clean install -DskipTests &> maven-notests-err-out
- tail -50 maven-notests-err-out

before_script:
- bash .travis/start-postgres.sh $(pwd) ${DB_NAME} ${DB_USER} ${DB_PASSWORD} ${DB_HOST} ${DB_PORT} &> postgres-start-err-out
- tail -50 postgres-start-err-out

script: 
- travis_wait mvn clean install -DskipITs=false -Dlog4j.configurationFile=.travis/log4j.properties -Dseqware_meta_db_host=${DB_HOST} -Dseqware_meta_db_port=${DB_PORT} -Dseqware_meta_db_name=${DB_NAME} -Dseqware_meta_db_user=${DB_USER} -Dseqware_meta_db_password=${DB_PASSWORD} &> maven-its-err-out

after_failure:
- tail -500 maven-its-err-out| grep -E 'ERROR|FAILURE'
- docker ps -a

